name: Android CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-and-test:
    name: Build & Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  # Use 11 or 17 depending on your Gradle setup

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Clean project
        run: ./gradlew clean

      - name: Build debug APK (verify build)
        run: ./gradlew assembleDebug

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      # Optional: Upload APK artifact
#      - name: Upload APK
#        uses: actions/upload-artifact@v4
#        with:
#          name: app-debug.apk
#          path: app/build/outputs/apk/debug/app-debug.apk
